### ISSUE TITLE
Blipp not working with fastify 4

### ISSUE THREAD

**Issue by cope** [PavelPolyakov/fastify-blipp#18]
We upgraded to fastify 4 and blipp is no longer reporting the routes correctly 😞 

It falsely reports some GET routes as HEAD and that is all.

Everything was working perfectly fine with fastify 3 😞

**Comment by PavelPolyakov** [comment]
hi @cope, probably there is some backward incompatibility, I'll try to check this week.

**Comment by PavelPolyakov** [comment]
@cope [here](https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e), under `Route registration is now synchronous`, it seems that plugin registration shall be synchronous in order to have `fastify-blipp` working.

This code works:
```js
const fastify = require("fastify")();
const fp = require("fastify-plugin");


const start = async () => {
  try {
    const plugin = fp(function(fastify, opts, next) {
        fastify.addHook("onRoute", routeOptions => {
            console.log('--- 1 ---', JSON.stringify(routeOptions), '---');
          });
        next()
    })

    await fastify.register(plugin);


    fastify.addHook("onRoute", routeOptions => {
        console.log('--- 2 ---', JSON.stringify(routeOptions), '---');
      });

    fastify.get("/hello/:username", async (req, reply) => ({
      greeting: `Hello, ${req.params.username}`
    }));
    fastify.post("/hello", async (req, reply) => ({
      greeting: `Hello, ${req.body.username}`
    }));
    
    await fastify.listen({port:3000});

    console.log(`server listening on ${fastify.server.address().port}`);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

start();
```

Does that help your case?

**Comment by cope** [comment]
yeah, almost all other plugins are now under different names, this is clearly the reason

thanks for looking into it
