### ISSUE TITLE
Supress HEAD routes

### ISSUE THREAD

**Issue by Luizssauro** [PavelPolyakov/fastify-blipp#19]
Hello there.

I was wondering if there is an option to supress HEAD routes.

All my routes are "duplicated" because of this and i didn't found out how to disable or even if it's possible.

![image](https://user-images.githubusercontent.com/12937479/182080138-b485acb2-4702-46ed-aa6b-21b04c273590.png)

I'm using:
"fastify": "^4.3.0",
"fastify-blipp": "^3.1.0",

Thanks in advance.

**Comment by Luizssauro** [comment]
Yeah, sure, does't make sense to mute by default.

Can you point me where to start looking to see if i'll be able to contribute?

**Comment by PavelPolyakov** [comment]
For example, you can pass something like `{muteMethods: []}` to the `blipp` initialization.

And then you can filter muted methods here https://github.com/PavelPolyakov/fastify-blipp/blob/master/src/index.js#L35 and don't add them to the output.

+ test and `README.md` update.

**Comment by Luizssauro** [comment]
Great, as soon as i can i'll try and make a PR.

Thanks for the guidance.
