### ISSUE TITLE
Maintanance?

### ISSUE THREAD

**Issue by radaalinmihai** [PavelPolyakov/fastify-blipp#24]
Hey, I was wondering if this package is still being maintained. I saw that the other packages that had their prefix fastify-* already got renamed into @fastify/* but this one. If it's not being managed by anyone I'd very much like to take on this package 😄

**Comment by voxpelli** [comment]
@radaalinmihai Best course of action is probably to fork this one, make the changes you like, publish it as your own package and then eventually one day it could be upstreamed here and replaced this one or this one could be archived and point to yours

**Comment by PavelPolyakov** [comment]
Thanks for the message. I’m still alive and can do some maintenance :) MR’s are also welcome.

Is this issue only about the ***@***.***` and dependencies update or anything else?

**Comment by radaalinmihai** [comment]
Hi, sorry for the late response. Yes, about that and ESM support. If MR's are welcomed then, when I have time I'll try and do something myself here and submit a PR :)

**Comment by radaalinmihai** [comment]
Hey, me again. I am done with the changes, but I think I need permissions to push a new branch, can you help me out? @PavelPolyakov

**Comment by PavelPolyakov** [comment]
You usually fork the repo, then do your changes, then push and create the pull request. This is the default GitHub open source contribution.
